# Thi{"noiseKey":{"private":{"type":"Buffer","data":"AJPJ6Mx/JOCWWrcVSFMGak+viQwRK8g2r6L0jRLg/Gk="},"public":{"type":"Buffer","data":"DqtF64GddtMPkq7OwPhrwD+2UOn089yjfwYi0KMHnhA="}},"pairingEphemeralKeyPair":{"private":{"type":"Buffer","data":"EMO1bt18tmXtGUWTIhk0YMXCyRMW6IpvCrsxnH6N8FE="},"public":{"type":"Buffer","data":"XpEyDoRkd+uSjxvqpBJ5buqkX6EwwJmdXnR0+zF4vRs="}},"signedIdentityKey":{"private":{"type":"Buffer","data":"0MBK0r2fBLZwQ1VlwArMZYO23EkqPNg+Rctbx9MqwXs="},"public":{"type":"Buffer","data":"MmPe5+fTEcedC0lMG7JkInSWsOyvyYdGK+X3Iv1Dzjk="}},"signedPreKey":{"keyPair":{"private":{"type":"Buffer","data":"gHbHs1njBgkZHFbQrXHGTTQf33GRUXRYq2VS3qRmaUY="},"public":{"type":"Buffer","data":"Ssy3mrHwv39F1Liv7wsJpArCNbICHbHCugyUF/fhlVI="}},"signature":{"type":"Buffer","data":"81IsClzmDCzrMXIUp35Jafalq5Gb3C/GU8EQowOWxNVp7MmjJSFI1cuuGWu6MuXTakqVQYIjdPRveddV9JxWhg=="},"keyId":1},"registrationId":229,"advSecretKey":"O4g0OS626C8t35JTkRDc8qo0L6vLaCIwMayx1hYMZvM=","processedHistoryMessages":[],"nextPreKeyId":31,"firstUnuploadedPreKeyId":31,"accountSyncCounter":0,"accountSettings":{"unarchiveChats":false},"deviceId":"QmT4YrhkSSudDbS8-bU6iw","phoneId":"8a2c2189-3a3b-48d7-bc43-bbb052ba4136","identityId":{"type":"Buffer","data":"O/Ply/nh5Xc1SHU5jcg8qtDIu7s="},"registered":true,"backupToken":{"type":"Buffer","data":"vfoqh0TsmBwFRt6hkFeS2DPS4nE="},"registration":{},"pairingCode":"E16X6P6Z","me":{"id":"254742870459:56@s.whatsapp.net","lid":"257556656201887:56@lid"},"account":{"details":"CIGo0tQGEPKBm7QGGAUgACgA","accountSignatureKey":"Notn7sgL2y2dwKMZPOR6idxFtUHcPkevr8nx0PjJ3Uk=","accountSignature":"pQ8ZdJsHLThf9Ho2cHDM+i25sRXW+1nhNr0TXabhbEXTa3MJTK/MjRFAgMpWhzZ42LQcOzgWyCm4JH/v1MLPCw==","deviceSignature":"l5/T55tejheEc5M2kGcNO9LYIsYiiEgCfShBPpmjEidPog2/c8SJZh6hCsbD0ej4sroTso283fQF9NFfx8pTiA=="},"signalIdentities":[{"identifier":{"name":"254742870459:56@s.whatsapp.net","deviceId":0},"identifierKey":{"type":"Buffer","data":"BTaLZ+7IC9stncCjGTzkeoncRbVB3D5Hr6/J8dD4yd1J"}}],"platform":"android","routingInfo":{"type":"Buffer","data":"CAUIDQ=="},"lastAccountSyncTimestamp":1720107264,"lastPropHash":"3L7dFE","myAppStateKeyId":"AAAAACGp"}s workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
